name: unicorn_shelf
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  unicorn: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  unicorn:
    path: ../unicorn
