name: unicorn_codegen
description: Code generation support for Unicorn.
version: 0.0.1
repository: https://github.com/dart-unicorn/unicorn

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
