name: ci
on:
  push:
    branches:
      - main
      - dev
      - "feat/**"
    paths:
      - ".github/workflows"
      - "lib/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows"
      - "lib/**"
jobs:
  test:
    strategy:
      matrix:
        sdk: [stable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{matrix.sdk}}
      - run: dart pub get
      - run: dart test --coverage .
      - run: dart pub run coverage:format_coverage -i . -l > coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
