name: Pre-Release
on:
  push:
    branches:
      - pre-release/*/*
jobs:
  dry_run_publish:
    name: Dry-run publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - unicorn
          - unicorn_codegen
          - unicorn_shelf
    steps:
      - uses: actions/checkout@v3

      - name: Dry-run publish
        uses: k-paxian/dart-package-publisher@master
        with:
          dryRunOnly: true
          relativePath: ./packages/${{ matrix.package }}
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          suppressBuildRunner: true
          skipTests: true
