name: publish
on:
  push:
    branches:
      - release/**
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to pub.dev
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
          suppressBuildRunner: true
          skipTests: false
