name: Release
on:
  push:
    branches:
      - release/*/*
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - unicorn
          - unicorn_codegen
          - unicorn_shelf
    steps:
      - uses: actions/checkout@v3

      - id: publish
        name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@master
        with:
          relativePath: ./packages/${{ matrix.package }}
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          suppressBuildRunner: true
          skipTests: false

      - if: steps.publish.outputs.success
        name: Tag commit
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
