name: Release
on:
  push:
    branches:
      - release/*/*
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - unicorn
          - unicorn_codegen
          - unicorn_shelf
    steps:
      - name: Check
        id: check
        run: |
          echo "is_satisfied=${{startsWith(github.ref_name, format('refs/heads/pre-release/{0}', ${{ matrix.package }}))}}" >> $GITHUB_OUTPUT

      - if: steps.check.outputs.is_satisfied
        uses: actions/checkout@v3

      - if: steps.check.outputs.is_satisfied
        id: publish
        name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@master
        with:
          relativePath: ./packages/${{ matrix.package }}
          credentialJson: ${{ secrets.PUB_CREDENTIAL_JSON }}
          suppressBuildRunner: true
          skipTests: false

      - if: steps.check.outputs.is_satisfied && steps.publish.outputs.success
        name: Tag commit
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
